//
//  Models.swift
//  
//
//  Created by Adrian Corscadden on 2020-07-03.
//

import Foundation

typealias SupportedList = [String]
typealias CoinList = [Coin]

public struct Pong: Codable {
    let gecko_says: String
}

public struct Coin: Codable {
    let id: String
    let symbol: String
    let name: String
}


public enum CoinGeckoCodes {
    public static let map = ["BTC" : "bitcoin",
    "BCH" : "bitcoin-cash",
    "ETH" : "ethereum",
    "HBAR" : "hedera-hashgraph",
    "XRP" : "ripple",
    "1ST" : "first-blood",
    "ABT" : "arcblock",
    "ADT" : "adtoken",
    "ADX" : "adex",
    "AE" : "aeternity",
    "AGI" : "singularitynet",
    "AION" : "aion",
    "AMB" : "amber",
    "AMLT" : "coinfirm-amlt",
    "ANT" : "aragon",
    "APPC" : "appcoins",
    "ARN" : "aeron",
    "ATMI" : "atonomi",
    "AUTO" : "cube",
    "BIX" : "bibox-token",
    "BLZ" : "bluzelle",
    "BNB" : "binancecoin",
    "BNT" : "bancor",
    "BRD" : "bread",
    "BTM" : "bytom",
    "CAS" : "cashaa",
    "CFI" : "cofound-it",
    "CMT" : "cybermiles",
    "CND" : "cindicator",
    "CNN" : "cnn",
    "CRPT" : "crypterium",
    "CS" : "credits",
    "CSP" : "caspian",
    "CVC" : "civic",
    "DAI" : "dai",
    "DENT" : "dent",
    "DGD" : "digixdao",
    "DNT" : "district0x",
    "DOV" : "dovu",
    "DRGN" : "dragonchain",
    "EDG" : "edgeless",
    "EDO" : "eidoo",
    "ELF" : "aelf",
    "ENG" : "enigma",
    "ENJ" : "enjincoin",
    "EOS" : "eos",
    "FSN" : "fsn",
    "FUN" : "funfair",
    "FXC" : "flexacoin",
    "GBX" : "globitex",
    "GNO" : "gnosis",
    "GNT" : "golem",
    "GNX" : "genaro-network",
    "GTO" : "gifto",
    "GUP" : "matchpool",
    "GUSD" : "gemini-dollar",
    "GVT" : "genesis-vision",
    "HPB" : "high-performance-blockchain",
    "HYDRO" : "hydro",
    "ICN" : "ic-node",
    "ICX" : "icon",
    "IOST" : "iostoken",
    "ITC" : "iot-chain",
    "IXT" : "insurex",
    "KIN" : "kin",
    "KNC" : "kyber-network",
    "LEND" : "ethlend",
    "LINK" : "chainlink",
    "LOOM" : "loom-network",
    "LRC" : "loopring",
    "LUN" : "lunyr",
    "MAN" : "matrix-ai-network",
    "MANA" : "decentraland",
    "MCO" : "monaco",
    "MKR" : "maker",
    "MTL" : "metal",
    "MYST" : "mysterium",
    "NAS" : "nebulas",
    "NEXO" : "nexo",
    "NMR" : "numeraire",
    "NPXS" : "pundi-x",
    "NULS" : "nuls",
    "OMG" : "omisego",
    "OST" : "simple-token",
    "OXT" : "orchid-protocol",
    "PAL" : "policypal",
    "PAX" : "paxos-standard",
    "PAY" : "tenx",
    "POE" : "poet",
    "POLY" : "polymath-network",
    "POWR" : "power-ledger",
    "PPT" : "populous",
    "PTOY" : "patientory",
    "QASH" : "qash",
    "QRL" : "quantum-resistant-ledger",
    "QSP" : "quantstamp",
    "RCC" : "reality-clash",
    "RCN" : "ripio-credit-network",
    "RDN" : "raiden-network",
    "REP" : "augur",
    "REQ" : "request-network",
    "REV" : "revain",
    "RLC" : "iexec-rlc",
    "RUFF" : "ruff",
    "RVT" : "rivetz",
    "SAI" : "sai",
    "SALT" : "salt",
    "SAN" : "santiment-network-token",
    "SENT" : "sentinel-group",
    "SNC" : "suncontract",
    "SNGLS" : "singulardtv",
    "SNM" : "sonm",
    "SNT" : "status",
    "SRN" : "sirin-labs-token",
    "STK" : "stk",
    "STMX" : "storm",
    "STORJ" : "storj",
    "STQ" : "storiqa",
    "STU" : "bitjob",
    "STX" : "stox",
    "SUB" : "substratum",
    "TEL" : "telcoin",
    "THETA" : "theta-token",
    "TIME" : "chronobank",
    "TRX" : "tron",
    "TUSD" : "true-usd",
    "UCASH" : "ucash",
    "USDC" : "usd-coin",
    "VEE" : "blockv",
    "VGX" : "ethos",
    "VIB" : "viberate",
    "WINGS" : "wings",
    "WPR" : "wepower",
    "WRC" : "worldcore",
    "WTC" : "waltonchain",
    "XUC" : "exchange-union",
    "ZIL" : "zilliqa",
    "ZLA" : "zilla",
    "ZRX" : "0x",
    "NCASH" : "nucleus-vision",
    "BAT": "basic-attention-token",
    "GD": "chainzilla",
    "STORM": "stormx",
    "WAX": "wax",
    "USDT20": "tether"
    ]

}
